# ============================================================
# VSURF Feature Selection on Labeled Training Data (8 Cities)
# ------------------------------------------------------------
# Purpose:
#   This script performs feature selection using VSURF on the
#   IDEABench x City Segments labeled training data.
#   It uses the labeled CSVs generated by 02_create_labeled_data.ipynb
#   (one CSV per training city, stored in 1_preprocessing/LabelledData_For_RF/).
#
# Method:
#   VSURF is run three times with different forest sizes
#   (ntree = 800, 1000, 1200). Variables selected at the prediction
#   stage (varselect.pred) are recorded for each run. The stable
#   intersection across all three runs defines the final predictor
#   subset used in the production RF model.
#
# Inputs:
#   1_preprocessing/LabelledData_For_RF/*_labeled_thr030.csv
#   (CSVs are committed to the repository)
#
# Outputs (saved to disk for auditability):
#   2_modelling/01_training/rf_outputs_full/tables/
#     vsurf_selected_variables_by_ntree.csv  -- variables per run
#     vsurf_intersection_variables.csv        -- stable intersection
#     vsurf_run_metadata.txt                  -- run provenance
#   2_modelling/01_training/rf_outputs_full/plots/
#     vsurf_selected_variables_venn.png       -- Venn diagram
#
# Random seed: 42 (set inside run_vsurf() before each VSURF call).
# ============================================================

# --- Safeguard: prevent re-running in same R session ----------
if (exists("vsurf_script_has_run") && isTRUE(vsurf_script_has_run)) {
  stop("This script has already run in this R session.")
}
vsurf_script_has_run <- TRUE

# --- 1. Load required libraries --------------------------------
suppressPackageStartupMessages({
  library(data.table)
  library(VSURF)
  library(VennDiagram)
  library(gridExtra)
})

# --- 2. Repo-root detection and paths --------------------------
find_repo_root <- function(start = getwd(), repo_name = "citysegmentdeprivation") {
  current <- normalizePath(start, winslash = "/", mustWork = TRUE)
  repeat {
    if (basename(current) == repo_name) return(current)
    parent <- dirname(current)
    if (parent == current) stop("Could not find repository root named ", repo_name)
    current <- parent
  }
}

REPO_ROOT    <- find_repo_root()
LABELLED_DIR <- file.path(REPO_ROOT, "1_preprocessing", "LabelledData_For_RF")
OUT_DIR      <- file.path(REPO_ROOT, "2_modelling", "01_training", "rf_outputs_full", "tables")
PLOTS_DIR    <- file.path(REPO_ROOT, "2_modelling", "01_training", "rf_outputs_full", "plots")

dir.create(OUT_DIR,   recursive = TRUE, showWarnings = FALSE)
dir.create(PLOTS_DIR, recursive = TRUE, showWarnings = FALSE)

message("REPO_ROOT:    ", REPO_ROOT)
message("LABELLED_DIR: ", LABELLED_DIR)
message("OUT_DIR:      ", OUT_DIR)
message("PLOTS_DIR:    ", PLOTS_DIR)

# --- 3. Read all labeled CSVs ----------------------------------
csv_files <- list.files(
  LABELLED_DIR,
  pattern = "_labeled_thr030\\.csv$",
  full.names = TRUE
)

if (length(csv_files) == 0) {
  stop("No *_labeled_thr030.csv files found in: ", LABELLED_DIR)
}

message("Found ", length(csv_files), " labeled training files.")

data_list <- lapply(csv_files, fread)
data <- rbindlist(data_list, fill = TRUE)

# --- 4. Keep only rows with labels ------------------------------
data <- data[!is.na(slum_label1)]
data$slum_label1 <- as.factor(data$slum_label1)

# --- 5. Feature list --------------------------------------------
features <- c(
  "POP_SEG", "AREAHA_SEG", "ROAD_SEG",
  "PAR_N_SEG", "PARU_N_SEG", "PARU_P_SEG",
  "PARU_A_SEG", "PAR_CV_SEG",
  "B_AREA_SEG", "B_AVG_SEG", "B_CV_SEG",
  "i1_pop_area", "i2_pop_par", "i3_pop_paru", "i4_pop_roads",
  "i5_par_area", "i6_paru_area", "i7_roads_area",
  "i8_paru_par", "i9_roads_par", "i10_roads_paru",
  "REG1_GHSL"
)

missing_feats <- setdiff(features, colnames(data))
if (length(missing_feats) > 0) {
  stop("Missing feature columns in labeled data: ",
       paste(missing_feats, collapse = ", "))
}

# Extract predictors and target
X <- data[, ..features]
y <- data$slum_label1

# Remove NA rows
complete <- complete.cases(X)
X <- X[complete, ]
y <- y[complete]

message("Rows after NA filtering: ", nrow(X))

# --- 6. Function to run VSURF -----------------------------------
run_vsurf <- function(ntree_value) {
  set.seed(42)
  result <- VSURF(
    X, y,
    ntree    = ntree_value,
    parallel = TRUE
  )

  list(
    pred   = colnames(X)[result$varselect.pred],
    interp = colnames(X)[result$varselect.interp]
  )
}

# --- 7. Run VSURF for multiple ntree values ----------------------
ntree_values <- c(800, 1000, 1200)
results <- list()

for (nt in ntree_values) {
  cat("\nRunning VSURF with ntree =", nt, "...\n")
  res <- run_vsurf(nt)
  results[[as.character(nt)]] <- res
  cat("Completed ntree =", nt,
      "| Selected predictors:", length(res$pred), "\n")
}

# --- 8. Display selected variables -------------------------------
cat("\nVSURF Selected Variables Summary:\n")

for (nt in ntree_values) {
  key <- as.character(nt)
  cat("\nntree =", nt, "\n")
  cat("Prediction variables:\n")
  print(results[[key]]$pred)
  cat("\nInterpretation variables:\n")
  print(results[[key]]$interp)
}

# --- 9. Compute stable intersection across ntree runs ------------
pred_sets   <- lapply(results, function(r) r$pred)
stable_vars <- Reduce(intersect, pred_sets)

cat("\nStable intersection of prediction variables (all 3 ntree runs):\n")
print(stable_vars)

# --- 10. Save outputs to disk -----------------------------------

# 10a. Per-run selected variables — long format
rows_pred <- do.call(rbind, lapply(names(results), function(nt) {
  vars <- results[[nt]]$pred
  if (length(vars) == 0) return(NULL)
  data.frame(ntree = as.integer(nt), stage = "pred", variable = vars,
             stringsAsFactors = FALSE)
}))

rows_interp <- do.call(rbind, lapply(names(results), function(nt) {
  vars <- results[[nt]]$interp
  if (length(vars) == 0) return(NULL)
  data.frame(ntree = as.integer(nt), stage = "interp", variable = vars,
             stringsAsFactors = FALSE)
}))

vars_long <- rbind(rows_pred, rows_interp)

write.csv(
  vars_long,
  file.path(OUT_DIR, "vsurf_selected_variables_by_ntree.csv"),
  row.names = FALSE
)
message("Saved: vsurf_selected_variables_by_ntree.csv")

# 10b. Stable intersection
write.csv(
  data.frame(variable = stable_vars, stringsAsFactors = FALSE),
  file.path(OUT_DIR, "vsurf_intersection_variables.csv"),
  row.names = FALSE
)
message("Saved: vsurf_intersection_variables.csv")

# 10c. Run metadata
vsurf_version <- tryCatch(
  as.character(packageVersion("VSURF")),
  error = function(e) "unknown"
)

meta_lines <- c(
  "VSURF run metadata",
  "==================",
  paste0("Date/time:              ", format(Sys.time(), "%Y-%m-%d %H:%M:%S %Z")),
  paste0("Input folder:           ", LABELLED_DIR),
  paste0("CSV files loaded:       ", length(csv_files)),
  paste0("Rows (after NA filter): ", nrow(X)),
  paste0("Columns (candidates):   ", ncol(X)),
  paste0("ntree values:           ", paste(ntree_values, collapse = ", ")),
  paste0("Random seed:            42  (set inside run_vsurf() before each VSURF call)"),
  paste0("VSURF version:          ", vsurf_version),
  "",
  "Note: The production RF model uses the stable intersection of",
  "varselect.pred variables selected across all three ntree runs.",
  paste0("Stable intersection: ", paste(stable_vars, collapse = ", "))
)

writeLines(meta_lines, file.path(OUT_DIR, "vsurf_run_metadata.txt"))
message("Saved: vsurf_run_metadata.txt")

# --- 11. Venn diagram — save to PNG ------------------------------
venn_sets <- list()
for (nt in ntree_values) {
  venn_sets[[paste0("ntree_", nt)]] <- results[[as.character(nt)]]$pred
}

venn_png <- file.path(PLOTS_DIR, "vsurf_selected_variables_venn.png")

if (length(venn_sets) == 3) {
  png(venn_png, width = 800, height = 700, res = 120)
  grid.newpage()
  draw.triple.venn(
    area1 = length(venn_sets[[1]]),
    area2 = length(venn_sets[[2]]),
    area3 = length(venn_sets[[3]]),
    n12   = length(intersect(venn_sets[[1]], venn_sets[[2]])),
    n23   = length(intersect(venn_sets[[2]], venn_sets[[3]])),
    n13   = length(intersect(venn_sets[[1]], venn_sets[[3]])),
    n123  = length(Reduce(intersect, venn_sets)),
    category = names(venn_sets),
    fill     = c("skyblue", "salmon", "palegreen"),
    alpha    = 0.5,
    cex      = 1.4,
    cat.cex  = 1.2
  )
  dev.off()
  message("Saved: ", venn_png)
} else {
  cat("Venn diagram requires exactly 3 ntree sets.\n")
}

cat("\nVSURF feature selection complete.\n")
